defaults:
  - hydra: jobname_outputdir_format
#######

run_config: #dragonfly
  exec_type: parallel # sequential
  gpu_ids: [0,1,2,3] #[2,3]
  runs_per_gpu: 1

seeds: 
  - 0

sweep:
  type: grid
  axes:
    - parameter: trainer.erank.loss_weight
      vals: [0.0, 1.0, 10, 50, 100, 500, 1000]
    - parameter: data.dataset_split.train_task_idx
      vals: [10] #[10, 11, 12]
### 
config:
  experiment_data:
    project_name: erank_supervised
    experiment_tag: '5.16'
    experiment_name: cf10-${config.experiment_data.experiment_tag}-cnn_nobn_pretrain-erankweight_${config.trainer.erank.loss_weight}-taskidx_${config.data.dataset_split.train_task_idx}
    experiment_dir: null
    seed: 0
    gpu_id: 2

  wandb:
    tags: # list(), used to tag wandblogger
      - ${config.experiment_data.experiment_tag}_exps
    notes:  # str, used to make notes to wandblogger
    
    watch:
      log: parameters #null #all
      log_freq: 3000

  model:
    name: cnn2d
    out_channels: 512
    batch_norm: false
    model_kwargs:
      image_size: 32
      input_channels: 3
      act_fn: relu
      layer_configs:
        - out_channels: ${config.model.out_channels}
          kernel_size: 3
          batch_norm: ${config.model.batch_norm}
          stride: 1
          padding: 0
          max_pool_kernel_size: 2
        - out_channels: ${config.model.out_channels}
          kernel_size: 3
          batch_norm: ${config.model.batch_norm}
          stride: 1
          padding: 0
          max_pool_kernel_size: 2
        - out_channels: ${config.model.out_channels}
          kernel_size: 3
          batch_norm: ${config.model.batch_norm}
          stride: 1
          padding: 0
          max_pool_kernel_size: 2
      linear_output_units:
        - 10

  trainer:
    n_epochs: 1000
    val_every: 1
    save_every: 400
    early_stopping_patience: 1000
    batch_size: 64
    optimizer_scheduler:
      optimizer_name: adamw
      optimizer_kwargs:
        lr: 0.001
        weight_decay: 0.0 #0.0001
    init_model: /system/user/beck/pwbeck/projects/regularization/erank/outputs/cf10-5.15-cnn_nobn_pretrain-taskidx_XXX_190722_171816/outputs/cf10-5.15-cnn_nobn_pretrain-taskidx_10-seed0_190722_171820/model_epoch_000.p
    loss: crossentropy
    erank:
      type: pretraindiff #none #random #pretraindiff
      loss_weight: XXX
      dir_buffer: /system/user/beck/pwbeck/projects/regularization/erank/outputs/cf10-5.15-cnn_nobn_pretrain-taskidx_XXX_190722_172137/outputs
      buffer_size: 10 # number of directions stored in the buffer
      norm_directions: False
      use_abs_model_params: True
    num_workers: 4

  data: 
    dataset: cifar10
    dataset_kwargs:
      dataset_dir: /system/user/beck/pwbeck/data/cifar
    dataset_split:
      train_val_split: 0.8
      num_train_tasks: 13
      subsplit_first_n_train_tasks: 0
      num_subsplit_tasks: 0
      train_task_idx: XXX