defaults:
  - hydra: jobname_outputdir_format
#######

run_config: #ocelot3
  exec_type: parallel # sequential
  gpu_ids: [0]
  runs_per_gpu: 5

seeds: 
  - 0

sweep:
  type: grid
  axes:
    - parameter: trainer.erank.loss_weight
      vals: [0.0, 1.0, 10, 100, 500, 1000]
    - parameter: data.dataset_split.restrict_n_samples_train_task
      vals: [100, 1000, 2000]
    - parameter: data.dataset_split.train_task_idx
      vals: [10] #[10, 11, 12]
### 
config:
  experiment_data:
    project_name: erank_supervised
    experiment_tag: '5.18'
    experiment_name: cf10-${config.experiment_data.experiment_tag}-fc_erank_absmodel_datasetsize-erankweight_${config.trainer.erank.loss_weight}-datasetsize_${config.data.dataset_split.restrict_n_samples_train_task}-taskidx_${config.data.dataset_split.train_task_idx}
    experiment_dir: null
    seed: 0
    gpu_id: 2

  wandb:
    tags: # list(), used to tag wandblogger
      - ${config.experiment_data.experiment_tag}_exps
      - erank
      - absmodel
    notes: Erank with 2 layer fc on CIFAR10. # str, used to make notes to wandblogger
    
    watch:
      log: parameters #null #all
      log_freq: 7000

  model:
    name: fc
    model_kwargs:
      input_size: 3072 # 3x32x32
      hidden_sizes:
        - 512
        - 512
      output_size: 10
      flatten_input: true
      dropout: 0.2
      act_fn: relu

  trainer:
    n_epochs: 2000
    val_every: 1
    save_every: 2000
    early_stopping_patience: 2000
    batch_size: 256
    optimizer_scheduler:
      optimizer_name: adamw
      optimizer_kwargs:
        lr: 0.0001
        weight_decay: 0.0 #0.01
    init_model: /system/user/publicwork/beck/projects/regularization/erank/outputs/cf10-5.2-fc_hypsearch-lr_XXX-wd_XXX-batchsizeXXX-taskidx_XXX_150722_145132/outputs/cf10-5.2-fc_hypsearch-lr_0.0001-wd_0.01-batchsize256-taskidx_10-seed0_150722_145222/model_epoch_000.p
    loss: crossentropy
    erank:
      type: pretraindiff #none #random #pretraindiff
      loss_weight: XXX
      dir_buffer: /system/user/publicwork/beck/projects/regularization/erank/outputs/cf10-5.5-fc_pretrain-taskidx_XXX_160722_115452/outputs
      buffer_size: 10 # number of directions stored in the buffer
      norm_directions: False
      use_abs_model_params: True
    num_workers: 4

  data: 
    dataset: cifar10
    dataset_kwargs:
      dataset_dir: /system/user/beck/pwbeck/data/cifar
    dataset_split:
      train_val_split: 0.8
      num_train_tasks: 13
      subsplit_first_n_train_tasks: 0
      num_subsplit_tasks: 0
      train_task_idx: XXX
      restrict_n_samples_train_task: XXX