defaults:
  - hydra: jobname_outputdir_format
#######

run_config: # eagle
  exec_type: parallel # sequential
  gpu_ids: [2,3]
  runs_per_gpu: 12

seeds: 
  - 0

sweep:
  type: grid
  axes:
    - parameter: data.dataset_split.train_task_idx
      vals: [0,1,2,3,4,5,6,7,8,9] #[10, 11, 12]
### 
config:
  experiment_data:
    project_name: erank_supervised
    experiment_tag: '5.5'
    experiment_name: cf10-${config.experiment_data.experiment_tag}-fc_pretrain-taskidx_${config.data.dataset_split.train_task_idx}
    experiment_dir: null
    seed: 0
    gpu_id: 2

  wandb:
    tags: # list(), used to tag wandblogger
      - ${config.experiment_data.experiment_tag}_exps
      - pretrain
    notes: Pretraining for 2 layer fc on CIFAR10. # str, used to make notes to wandblogger
    
    watch:
      log: null #all
      log_freq: 100

  model:
    name: fc
    model_kwargs:
      input_size: 3072 # 3x32x32
      hidden_sizes:
        - 512
        - 512
      output_size: 10
      flatten_input: true
      dropout: 0.2
      act_fn: relu

  trainer:
    n_epochs: 400
    val_every: 1
    save_every: 100
    early_stopping_patience: 40
    batch_size: 256
    optimizer_scheduler:
      optimizer_name: adamw
      optimizer_kwargs:
        lr: 0.0001
        weight_decay: 0.01
    init_model: /system/user/publicwork/beck/projects/regularization/erank/outputs/cf10-5.2-fc_hypsearch-lr_XXX-wd_XXX-batchsizeXXX-taskidx_XXX_150722_145132/outputs/cf10-5.2-fc_hypsearch-lr_0.0001-wd_0.01-batchsize256-taskidx_10-seed0_150722_145222/model_epoch_000.p
    loss: crossentropy
    erank:
      type: none #random #pretraindiff
      loss_weight: 0.0
      dir_buffer: null
      buffer_size: 10 # number of directions stored in the buffer
      norm_directions: False
      use_abs_model_params: True
    num_workers: 4

  data: 
    dataset: cifar10
    dataset_kwargs:
      dataset_dir: /system/user/beck/pwbeck/data/cifar
    dataset_split:
      train_val_split: 0.8
      num_train_tasks: 13
      subsplit_first_n_train_tasks: 0
      num_subsplit_tasks: 0
      train_task_idx: XXX