defaults:
  - hydra: jobname_outputdir_format
  - _self_
#######
hydra:
  verbose: ${config.trainer.verbose}
#######
run_config:
  exec_type: parallel # sequential
  hostname: dragonfly
  gpu_ids: [0, 1, 2, 3]
  runs_per_gpu: 2

  wandb: # wandb config for run_handler, if "wandb: null" then logging to wandb is disabled for run_handler
    init:
      tags:
        - ${config.experiment_data.experiment_tag}_exps
        - run_handler
      notes: #
      group: ${config.experiment_data.experiment_tag}
      job_type: run_handler

seeds:
  - 0

sweep:
  type: grid
  axes:
    - parameter: trainer.task_batch_size
      vals: [10] #[1, 5, 10]
    - parameter: trainer.n_inner_iter
      vals: [100] #[10, 30, 100]
    - parameter: trainer.regularizer.regularizer_kwargs.loss_coefficient
      vals: [0.0, 0.1, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0]

start_num: 1 # use this to count how often this config is run

###
config:
  experiment_data:
    entity: jkuiml-fsl # null
    project_name: erank_meta
    experiment_tag: "7.10"
    experiment_name: sinus-${config.experiment_data.experiment_tag}.${start_num}-${config.trainer.regularizer.type}_backlog-loss_coeff-${config.trainer.regularizer.regularizer_kwargs.loss_coefficient}-task_bs-${config.trainer.task_batch_size}-inner_iter-${config.trainer.n_inner_iter}
    experiment_dir: null
    seed: 0
    hostname: null # the server on which the run is run, will be filled by run_handler
    gpu_id: 0

  wandb:
    init:
      tags: # list(), used to tag wandblogger
        - ${config.experiment_data.experiment_tag}_exps
        - dotproduct
      notes: Hyperparameter search (loss_coefficient) for dotproduct regularization with new variant, i.e. normalized mean of subspace vecs (itsel unnormalized). # str, used to make notes to wandblogger
      group: ${config.experiment_data.experiment_tag} # null
      job_type: startnum_${start_num} # examples: hypsearch, pretrain, eval, etc.

    watch:
      log: null #parameters #null #all
      log_freq: 5000

  model:
    name: fc
    model_kwargs:
      input_size: 1
      hidden_sizes:
        - 64
        - 64
      output_size: 1
      flatten_input: true # can probably use also false
      dropout: null
      act_fn: relu

  trainer:
    training_setup: reptile
    n_epochs: 10e6 # number of iterations (outer/meta gradient steps)
    log_train_epoch_every: 20 #10
    val_every: 0.5e3
    val_mode: reg # noreg: do not use regularizers, reg: use regularizers
    save_every: 10e6 # do not save during training manually
    early_stopping_patience: 20e3 # outer update steps
    task_batch_size: XXX #1 #5 # meta-batch size (number of tasks sampled per iteration)
    optimizer_scheduler:
      optimizer_name: sgd #adamw 
      optimizer_kwargs:
        lr: 0.1 #0.001 # default sine: 0.001
        weight_decay: 0.0 #0.001
    init_model: null
    inner_optimizer:
      optimizer_name: sgd
      optimizer_kwargs:
        lr: 0.001 # default sine: 0.01
    n_inner_iter: XXX #100 #3
    val_pred_plots_for_tasks: 2 #1 # Prediction plots for `val_plots` tasks. If int: Uses the first `val_plots` tasks to generate plots
    inner_eval_after_steps: [0, 1, 2, 3, 5, 10, 20, 30, 50] # null: use default, List[int]: list of steps after, which eval is done
    log_plot_inner_learning_curves:
      - loss_key: loss_total
      - loss_key: loss_MSELoss
      - loss_key: loss_${config.trainer.regularizer.type}
        ylimits: [-1, 1] # ylimits of plot [lower, upper]

    loss: mse
    regularizer:
      type: dotproduct # erank # none
      init_type: buffer #weightsdiff #random #buffer
      init_dir_buffer: null
      regularizer_kwargs:
        loss_coefficient: XXX
        buffer_size: ${config.trainer.task_batch_size} #10 # number of directions stored in the buffer
        buffer_mode: backlog # none, backlog, queue
        optim_model_vec_mode: basediff #abs #basediff # abs, stepdiff, basediff
        subspace_vecs_mode: basediff #abs #basediff # abs, initdiff, basediff
        track_last_n_model_steps: 0
        normalize_dir_matrix_m: False
    metrics:
      - MeanSquaredError
    num_workers: 4
    verbose: False #True

  data:
    metadataset: sinus
    train_metadataset_kwargs:
      support_size: 10
      query_size: 50
      num_tasks: 10000
      amplitude_range: [0.1, 5.0]
      phase_range: [0, 6.283185307]
      x_range: [-5, 5]
      regenerate_task_support_set: False
      seed: ${config.experiment_data.seed}
    val_metadataset_kwargs:
      support_size: 10
      query_size: 50
      num_tasks: 50 #100 #1000
      amplitude_range: [0.1, 5.0]
      phase_range: [0, 6.283185307]
      x_range: [-5, 5]
      regenerate_task_support_set: False
      seed: 1 # different from train dataset
