defaults:
  - hydra: jobname_outputdir_format
  - _self_
#######
hydra:
  verbose: ${config.trainer.verbose}
#######
run_config:
  exec_type: parallel # sequential
  hostname: fox
  gpu_ids: [0, 1]
  runs_per_gpu: 3

  wandb: # wandb config for run_handler, if "wandb: null" then logging to wandb is disabled for run_handler
    init:
      tags:
        - ${config.experiment_data.experiment_tag}_exps
        - run_handler
      notes: #
      group: ${config.experiment_data.experiment_tag}
      job_type: run_handler

seeds:
  - 0

sweep:
  type: grid
  axes:
    - parameter: trainer.task_batch_size
      vals: [10] #[1, 5, 10]
    - parameter: trainer.n_inner_iter
      vals: [30] #[100] #[10, 30, 100]
    - parameter: trainer.regularizer.regularizer_kwargs.loss_coefficient
      vals:  [0.0, 0.001, 0.01, 0.1, 0.25, 0.5, 1.0, 1.5, 2.0, 3.0, 5.0, 10.] #[0.0, 0.1, 0.5, 1.0, 1.5, 3.0, 5.0, 10.]
    - parameter: trainer.optimizer_scheduler.optimizer_kwargs.lr
      vals: [1.0] #[1.0, 0.5, 0.1, 0.01]
    - parameter: trainer.inner_optimizer.optimizer_kwargs.lr
      vals: [0.005, 0.001] #[0.01] # [0.1, 0.01, 0.001]

start_num: 1 # use this to count how often this config is run

###
config:
  experiment_data:
    entity: jkuiml-fsl # null
    project_name: erank_meta
    experiment_tag: "7.21"
    experiment_name: sinus-${config.experiment_data.experiment_tag}.${start_num}-${config.trainer.regularizer.type}_inf_tasks-loss_coeff-${config.trainer.regularizer.regularizer_kwargs.loss_coefficient}-olr-${config.trainer.optimizer_scheduler.optimizer_kwargs.lr}-ilr-${config.trainer.inner_optimizer.optimizer_kwargs.lr}-task_bs-${config.trainer.task_batch_size}-inner_iter-${config.trainer.n_inner_iter}
    experiment_dir: null
    seed: 0
    hostname: null # the server on which the run is run, will be filled by run_handler
    gpu_id: 0

  wandb:
    init:
      tags: # list(), used to tag wandblogger
        - ${config.experiment_data.experiment_tag}_exps
        - dotproduct
      notes: Erank lambda sweep on sinus inf tasks. # str, used to make notes to wandblogger
      group: ${config.experiment_data.experiment_tag} # null
      job_type: startnum_${start_num} # examples: hypsearch, pretrain, eval, etc.

    watch:
      log: null #parameters #null #all
      log_freq: 5000

  model:
    name: fc
    model_kwargs:
      input_size: 1
      hidden_sizes:
        - 40
        - 40
      output_size: 1
      flatten_input: true # can probably use also false
      dropout: null
      act_fn: relu

  trainer:
    training_setup: reptile
    n_epochs: 50e3 # number of iterations (outer/meta gradient steps)
    log_train_epoch_every: 20 #10
    log_additional_logs: False
    val_every: 0.2e3
    val_mode: reg # noreg: do not use regularizers, reg: use regularizers
    val_tasks_cfg: # [random / deterministic, num_tasks] #random: sample tasks randomly, on every iteration, # deterministic: use pregenerated tasks # num_tasks=-1 use all available
      selection_type: random
      num_tasks: 10
    save_every: 10e6 # do not save during training manually
    early_stopping_patience: 10e3 # outer update steps
    task_batch_size: XXX #1 #5 # meta-batch size (number of tasks sampled per iteration)
    optimizer_scheduler:
      optimizer_name: sgd
      optimizer_kwargs:
        lr: XXX # our sine: 0.1 # default sine: 0.001
        weight_decay: 0.0 #0.001
    init_model: null
    inner_optimizer:
      optimizer_name: sgd
      optimizer_kwargs:
        lr: XXX # our sine: 0.001 # default sine: 0.01
    n_inner_iter: XXX #100 #3
    # val_pred_plots_for_tasks: 0 #2 # Prediction plots for `val_plots` tasks. If int: Uses the first `val_plots` tasks to generate plots
    inner_eval_after_steps: 0 #[0, 1, 2, 3, 5, 10, 20, 30, 50] # null: use default, List[int]: list of steps after, which eval is done
    # log_plot_inner_learning_curves:
    #   - loss_key: loss_total
    #   - loss_key: loss_MSELoss
    #   - loss_key: loss_${config.trainer.regularizer.type}
    #     ylimits: [-1, 1] # ylimits of plot [lower, upper]

    loss: mse
    regularizer:
      type: dotproduct # dotproduct # none
      init_type: buffer #weightsdiff #random #buffer
      init_dir_buffer: null
      regularizer_kwargs:
        loss_coefficient: XXX
        buffer_size: ${config.trainer.task_batch_size} #10 # number of directions stored in the buffer
        buffer_mode: backlog # none, backlog, queue
        optim_model_vec_mode: basediff #abs #basediff # abs, stepdiff, basediff
        subspace_vecs_mode: basediff #abs #basediff # abs, initdiff, basediff
        track_last_n_model_steps: 0
        normalize_dir_matrix_m: False
    metrics:
      - MeanSquaredError
    num_workers: 4
    verbose: False #True

  data:
    metadataset: sinus
    train_metadataset_kwargs:
      support_size: 10
      query_size: 50
      amplitude_range: [0.1, 5.0]
      phase_range: [0, 6.283185307]
      x_range: [-5, 5]
      regenerate_task_support_set: False
    val_metadataset_kwargs:
      support_size: 10
      query_size: 50
      amplitude_range: [0.1, 5.0]
      phase_range: [0, 6.283185307]
      x_range: [-5, 5]
      regenerate_task_support_set: False
