name: cnn2d
out_channels: 64
out_units: 10
model_kwargs:
  image_size: 28
  in_channels: 1
  act_fn: relu
  layer_configs:
    - out_channels: ${out_channels}
      kernel_size: 3
      batch_norm: true
      stride: 1
      padding: 0
      max_pool_kernel_size: 2
    - out_channels: ${out_channels}
      kernel_size: 3
      batch_norm: true
      stride: 1
      padding: 0
      max_pool_kernel_size: 2
    - out_channels: ${out_channels}
      kernel_size: 3
      batch_norm: true
      stride: 1
      padding: 0
      # max_pool_kernel_size: {mp_kernel_size}
    - out_channels: ${out_channels}
      kernel_size: 3
      batch_norm: true
      stride: 1
      padding: 0
      # max_pool_kernel_size: {mp_kernel_size}
  linear_output_units:
    - ${out_units}