### HYDRA START
hydra:
  run:
    dir: outputs/${hydra.job.name}
  sweep:
    dir: outputs/${hydra.job.name}
    subdir: ${hydra.job.num}
  job:
    chdir: True # change working directory of run
    name: ${config.experiment_data.experiment_name}_${now:%d%m%y_%H%M%S}
### HYDRA END

run_config: # gorilla
  exec_type: parallel # sequential
  gpu_ids: [2,3,4,5]
  runs_per_gpu: 7

seeds: 
  - 0

sweep:
  type: grid
  axes:
    - parameter: data.train_task_idx
      vals: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]

### 
config:
  experiment_data:
    project_name: erank_supervised
    experiment_tag: '4.2'
    experiment_name: f_mnist-${config.experiment_data.experiment_tag}-pretrain30-taskidx_${config.data.train_task_idx}
    experiment_dir: null
    seed: 0
    gpu_id: 2

  tags: # list(), used to tag wandblogger
    - erank
    - ${config.experiment_data.experiment_tag}_exps
  notes: Training without erank. Obtain pretrained models. # str, used to make notes to wandblogger

  model:
    name: fc
    model_kwargs:
      input_size: 784
      hidden_sizes:
        - 512
        - 512
      output_size: 10
      flatten_input: true
      dropout: 0.2
      act_fn: relu

  trainer:
    n_epochs: 200
    val_every: 1
    save_every: 50
    early_stopping_patience: 20
    batch_size: 256
    optimizer_scheduler:
      optimizer_name: adam
      optimizer_kwargs:
        lr: 0.001
    init_model: /system/user/beck/pwbeck/projects/regularization/erank/res/init_model.p
    loss: crossentropy
    erank:
      type: none
      loss_weight: 0.0
      dir_buffer: /system/user/beck/pwbeck/projects/regularization/erank/outputs/f_mnist-2.0-taskidxXXX_260622_110634/outputs
      buffer_size: 10 # number of directions stored in the buffer
      norm_directions: False
      use_abs_model_params: True
    num_workers: 4

  data: 
    dataset: fashion_mnist
    dataset_dir: /system/user/beck/pwbeck/data/mnist
    train_val_split: 0.8
    num_train_tasks: 13
    subsplit_first_n_train_tasks: 10
    num_subsplit_tasks: 30
    train_task_idx: XXX

    normalizer: # mean and std per channel
      mean:
        - 0.2860
      std:
        - 0.3205