defaults:
  - hydra: jobname_outputdir_format
  - _self_
#######

run_config:
  exec_type: parallel # sequential
  hostname: scorpion
  gpu_ids: [1, 2, 3]
  runs_per_gpu: 8

  wandb: # wandb config for run_handler, if "wandb: null" then logging to wandb is disabled for run_handler
    init:
      tags:
        - ${config.experiment_data.experiment_tag}_exps
        - run_handler
      notes: #
      group: ${config.experiment_data.experiment_tag}
      job_type: run_handler

seeds:
  - 0

sweep:
  type: grid
  axes:
    - parameter: trainer.task_batch_size
      vals: [5]
    - parameter: trainer.n_inner_iter
      vals: [3, 5, 10, 30]
    - parameter: trainer.optimizer_scheduler.optimizer_kwargs.lr # outer lr
      vals: [0.1, 0.01, 0.005]
    - parameter: trainer.inner_optimizer.optimizer_kwargs.lr # inner lr
      vals: [1.0, 0.5, 0.1, 0.001]

start_num: 0 # use this to count how often this config is run

###
config:
  experiment_data:
    entity: jkuiml-fsl # null
    project_name: erank_meta
    experiment_tag: "6.1"
    experiment_name: sinus-${config.experiment_data.experiment_tag}.${start_num}-rep_gs-outer_lr-${config.trainer.optimizer_scheduler.optimizer_kwargs.lr}-inner_lr-${config.trainer.inner_optimizer.optimizer_kwargs.lr}-n_inner_iter-${config.trainer.n_inner_iter}-batch_size-${config.trainer.task_batch_size}
    experiment_dir: null
    seed: 0
    hostname: null # the server on which the run is run, will be filled by run_handler
    gpu_id: 0

  wandb:
    init:
      tags: # list(), used to tag wandblogger
        - ${config.experiment_data.experiment_tag}_exps
        - erank
      notes: Hyperparametersearch for own Reptile implementation # str, used to make notes to wandblogger
      group: ${config.experiment_data.experiment_tag} # null
      job_type: startnum_${start_num} # examples: hypsearch, pretrain, eval, etc.

    watch:
      log: null #parameters #null #all
      log_freq: 5000

  model:
    name: fc
    model_kwargs:
      input_size: 1
      hidden_sizes:
        - 64
        - 64
      output_size: 1
      flatten_input: true # can probably use also false
      dropout: null
      act_fn: relu

  trainer:
    training_setup: reptile
    n_epochs: 200000 # number of iterations (outer/meta gradient steps)
    log_train_epoch_every: 2000
    val_every: 5000
    save_every: 100000
    early_stopping_patience: null # no early stopping
    task_batch_size: XXX #1 #5 # meta-batch size (number of tasks sampled per iteration)
    optimizer_scheduler:
      optimizer_name: sgd #adamw # TODO implement optimizer state sharing between inner loops
      optimizer_kwargs:
        lr: XXX #0.001
        weight_decay: 0.0 #0.001
    init_model: null
    inner_optimizer:
      optimizer_name: sgd
      optimizer_kwargs:
        lr: XXX #0.01
    n_inner_iter: XXX #3
    val_pred_plots_for_tasks: 1 # Prediction plots for `val_plots` tasks. If int: Uses the first `val_plots` tasks to generate plots
    inner_eval_after_steps: [0, 1, 2, 3, 5, 10, 20, 30, 50] # null: use default, List[int]: list of steps after, which eval is done

    loss: mse
    # erank:
    #   type: none #pretraindiff #none #random #pretraindiff
    #   loss_weight: XXX
    #   dir_buffer: null
    #   buffer_size: 10 # number of directions stored in the buffer
    #   norm_directions: False
    #   use_abs_model_params: True
    num_workers: 4

  data:
    metadataset: sinus
    train_metadataset_kwargs:
      support_size: 10
      query_size: 50
      num_tasks: 10000
      amplitude_range: [0.1, 5.0]
      phase_range: [0, 6.283185307]
      x_range: [-5, 5]
      regenerate_task_support_set: False
      seed: 0 # this seed is only used for task generation
    val_metadataset_kwargs:
      support_size: 10
      query_size: 50
      num_tasks: 50 #100 #1000
      amplitude_range: [0.1, 5.0]
      phase_range: [0, 6.283185307]
      x_range: [-5, 5]
      regenerate_task_support_set: False
      seed: 1 # different from train dataset!
