### HYDRA START
hydra:
  run:
    dir: outputs/${hydra.job.name}
  sweep:
    dir: outputs/${hydra.job.name}
    subdir: ${hydra.job.num}
  job:
    chdir: True # change working directory of run
    name: ${config.experiment_data.experiment_name}_${now:%d%m%y_%H%M%S}
### HYDRA END

# run_config:
#   exec_type: parallel # sequential
#   gpu_ids: [2,3]
#   runs_per_gpu: 5

# seeds: 
#   - 0

# sweep:
#   type: grid
#   axes:
#     - parameter: data.train_task_idx
#       vals: [0,1,2,3,4,5,6,7,8,9]

### 
config:
  experiment_data:
    project_name: erank_supervised
    experiment_name: f_mnist-erank-DEBUG
    experiment_dir: null
    seed: 0
    gpu_id: 0

  wandb:
    tags: # list(), used to tag wandblogger
      - DEBUG
    notes: Trying different things. # str, used to make notes to wandblogger
    
    watch:
      log: all
      log_freq: 100

  model:
    name: fc
    model_kwargs:
      input_size: 784
      hidden_sizes:
        - 512
        - 512
      output_size: 10
      flatten_input: true
      dropout: 0.2
      act_fn: relu

  trainer:
    n_epochs: 100
    val_every: 1
    save_every: 50
    early_stopping_patience: 300
    batch_size: 256
    optimizer_scheduler:
      optimizer_name: adam
      optimizer_kwargs:
        lr: 0.001
    init_model: /system/user/beck/pwbeck/projects/regularization/erank/res/init_model.p
    loss: crossentropy
    erank:
      type: pretraindiff
      loss_weight: 1
      dir_buffer: /system/user/beck/pwbeck/projects/regularization/erank/outputs/f_mnist-2.0-taskidxXXX_260622_110634/outputs
      buffer_size: 10 # number of directions stored in the buffer
      norm_directions: False
      use_abs_model_params: True
    num_workers: 4

  data: 
    dataset: fashion_mnist
    dataset_kwargs:
      dataset_dir: /system/user/beck/pwbeck/data/mnist
      normalizer: # mean and std per channel
        mean:
          - 0.2860
        std:
          - 0.3205
    dataset_split:
      train_val_split: 0.8
      num_train_tasks: 13
      subsplit_first_n_train_tasks: 0
      num_subsplit_tasks: 0
      train_task_idx: 10