defaults:
  - hydra: jobname_outputdir_format
  - _self_
#######
hydra:
  verbose: ${config.trainer.verbose}
#######
run_config:
  exec_type: parallel # sequential
  hostname: max-pc
  gpu_ids: [0]
  runs_per_gpu: 4

  # wandb: # wandb config for run_handler, if "wandb: null" then logging to wandb is disabled for run_handler
  #   init:
  #     tags:
  #       - ${config.experiment_data.experiment_tag}_exps
  #       - run_handler
  #     notes: #
  #     group: ${config.experiment_data.experiment_tag}
  #     job_type: run_handler

seeds:
  - 0

sweep:
  type: grid
  axes:
    - parameter: trainer.regularizer.type
      vals: ["none"]

start_num: 0 # use this to count how often this config is run

###
config:
  experiment_data:
    entity: jkuiml-fsl
    project_name: sparsity
    experiment_tag: "DEBUG"
    experiment_type: startnum_${start_num}
    experiment_name: sl-mnist-${config.experiment_data.experiment_tag}.${start_num}
    experiment_dir: null
    experiment_notes: Debugging for supervised sinus.
    job_name: null
    seed: 0
    hostname: null # the server on which the run is run, will be filled by run_handler
    gpu_id: 0

  wandb:
    init:
      tags: # list(), used to tag wandblogger
        - ${config.experiment_data.experiment_tag}_exps
      notes: ${config.experiment_data.experiment_notes} # str, used to make notes to wandblogger
      group: ${config.experiment_data.experiment_tag} # null
      job_type: ${config.experiment_data.experiment_type} # examples: hypsearch, pretrain, eval, etc.

    watch:
      log: null #parameters #null #all
      log_freq: 5000

  model: 
    name: fc
    model_kwargs:
      input_size: 784
      hidden_sizes: 
        - 300
        - 100
      output_size: 10
      flatten_input: True
      dropout: null
      act_fn: relu

  trainer:
    training_setup: supervised
    n_epochs: 3
    # n_steps: 200
    log_train_step_every: 1
    log_additional_train_step_every_multiplier: 1
    log_additional_logs: False
    val_every: 5
    save_every: 10000
    early_stopping_patience: 50
    batch_size: 256
    optimizer_scheduler:
      optimizer_name: adamw #sgd #adamw
      optimizer_kwargs:
        lr: 0.001 #1.0 # our sine: 0.1 # default sine: 0.001
        weight_decay: 0.0 #0.001
    init_model: null

    loss: crossentropy

    metrics:
      - Accuracy
    num_workers: 4
    verbose: False #True

  data:
    dataset: mnist 
    dataset_kwargs:
      data_root_path: /home/max/phd/data
    dataset_split:
      train_val_split: 0.8
