hydra:
  run:
    dir: outputs/${hydra.job.name}
  sweep:
    dir: outputs/${hydra.job.name}
    subdir: ${hydra.job.num}
  job:
    chdir: True # change working directory of run
    name: ${experiment_data.experiment_name}_${now:%d%m%y_%H%M%S}


experiment_data:
  project_name: erank_supervised
  experiment_name: fashion_mnist
  experiment_dir: null
  seed: 0
  gpu_id: 0

tags: # list(), used to tag wandblogger
notes: # str, used to make notes to wandblogger

model:
  name: fc
  model_kwargs:
    input_size: 784
    hidden_sizes:
      - 512
      - 512
    output_size: 10
    flatten_input: true
    dropout: 0.2
    act_fn: relu



trainer:
  n_epochs: 5
  val_every: 1
  save_every: 5
  early_stopping_patience: 5
  batch_size: 256
  optimizer_scheduler:
    optimizer_name: sgd
    optimizer_kwargs:
      lr: 0.001
    
  
  num_workers: 4
  

data: 
  dataset: fashion_mnist
  dataset_dir: ./data
  normalizer: # mean and std per channel
    mean:
      - 0.2860
    std:
      - 0.3205