### HYDRA START
hydra:
  run:
    dir: outputs/${hydra.job.name}
  sweep:
    dir: outputs/${hydra.job.name}
    subdir: ${hydra.job.num}
  job:
    chdir: True # change working directory of run
    name: ${config.experiment_data.experiment_name}_${now:%d%m%y_%H%M%S}
### HYDRA END

run_config:
  exec_type: parallel # sequential
  gpu_ids: [2,3]
  runs_per_gpu: 4

seeds: 
  - 0

sweep:
  type: grid
  axes:
    - parameter: data.train_task_idx
      vals: [0,1,2,3,4,5,6,7,8,9]

### 
config:
  experiment_data:
    project_name: erank_supervised
    experiment_name: f_mnist-same_init2-taskidx${config.data.train_task_idx}
    experiment_dir: null
    seed: 0
    gpu_id: 2

  tags: # list(), used to tag wandblogger
    - hypsearch
    - same_init
  notes: Sweep over tasks # str, used to make notes to wandblogger

  model:
    name: fc
    model_kwargs:
      input_size: 784
      hidden_sizes:
        - 512
        - 512
      output_size: 10
      flatten_input: true
      dropout: 0.2
      act_fn: relu

  trainer:
    n_epochs: 50
    val_every: 1
    save_every: 5
    early_stopping_patience: 5
    batch_size: 256
    optimizer_scheduler:
      optimizer_name: adam
      optimizer_kwargs:
        lr: 0.001
    erank:
      type: XXX
      dir_buffer: /system/user/beck/pwbeck/projects/regularization/erank/outputs/240622_083655_f_mnist-same_init3-taskidxXXX/outputs
      buffer_size: 10 # number of directions stored in the buffer
    init_model: /system/user/beck/pwbeck/projects/regularization/erank/res/init_model.p

    num_workers: 4


  data: 
    dataset: fashion_mnist
    dataset_dir: /system/user/beck/pwbeck/data/mnist
    train_val_split: 0.8
    num_train_tasks: 12
    train_task_idx: XXX
    normalizer: # mean and std per channel
      mean:
        - 0.2860
      std:
        - 0.3205