defaults:
- hydra: jobname_outputdir_format
- _self_
run_config:
  exec_type: parallel
  hostname: wasp
  gpu_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  runs_per_gpu: 5
  wandb:
    init:
      tags:
      - ${config.experiment_data.experiment_tag}_exps
      - run_handler
      notes: null
      group: ${config.experiment_data.experiment_tag}
      job_type: run_handler
seeds:
- 1
- 2
sweep:
  type: grid
  axes:
  - parameter: trainer.init_model_step
    vals:
    - 0
    - 5
    - 10
    - 15
    - 20
    - 25
    - 30
    - 35
    - 40
    - 45
    - 50
    - 55
    - 60
    - 65
    - 70
    - 75
    - 80
    - 85
    - 90
    - 95
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275
    - 300
    - 325
    - 350
    - 375
    - 400
    - 425
    - 450
    - 475
  - parameter: data.dataset_kwargs.rotation_angle
    vals: linspace(0,180,30,endpoint=True)
  - parameter: data.dataset_split.restrict_n_samples_train_task
    vals:
    - 50
start_num: 4
config:
  experiment_data:
    entity: jkuiml-fsl
    project_name: sparsity
    experiment_tag: '11.7'
    experiment_type: startnum_${start_num}
    experiment_name: mnist-${config.experiment_data.experiment_tag}.${start_num}-lenet_rottasks_ft
    experiment_dir: null
    experiment_notes: Hyperparameter search.
    job_name: null
    seed: 0
    hostname: null
    gpu_id: 0
  model:
    name: fc
    model_kwargs:
      input_size: 784
      hidden_sizes:
      - 300
      - 100
      output_size: 10
      flatten_input: true
      dropout: null
      act_fn: relu
  trainer:
    training_setup: supervised
    n_steps: 2000
    log_train_step_every: 1
    log_additional_train_step_every_multiplier: 1
    log_additional_logs: true
    val_every: 5
    save_every: 5
    early_stopping_patience: 200
    batch_size: 128
    optimizer_scheduler:
      optimizer_name: adamw
      optimizer_kwargs:
        lr: 0.001
        weight_decay: 0.0
    init_model_step: XXX
    init_model: /system/user/beck/pwbeck/projects/regularization/erank/outputs/mnist-11.5.0-lenet--221015_122552/model_step_${config.trainer.init_model_step}.p
    loss: crossentropy
    metrics:
    - Accuracy
    num_workers: 4
    verbose: false
  data:
    dataset: rotatedvision
    dataset_kwargs:
      data_root_path: /system/user/beck/pwbeck/data
      dataset: mnist
      rotation_angle: XXX
    dataset_split:
      train_val_split: 0.8
      restrict_n_samples_train_task: XXX
__config_created: '2022-12-12 17:43:28'
__config_last_updated: '2022-12-12 17:43:28'
