config:

  run_script_name: instability_analyzer
  run_script_kwargs:
    instability_sweep: /system/user/publicwork/beck/projects/regularization/erank/outputs/mnist-11.7.3-lenet_rottasks_ft--221125_123651
    score_fn: TAccuracy
    interpolation_factors: [0.0000, 0.2500, 0.5000, 0.7500, 1.0000]
    init_model_idxes_ks_or_every: 0
    train_model_idxes: [100, -1]
    device: 1
    interpolate_linear_kwargs: 
      interpolation_on_train_data: True
      dataloader_kwargs:
        batch_size: 1024
      compute_model_distances: True
    override_files: True
    num_seed_combinations: 1
    save_folder_suffix: full
    float_eps_query_job: 1e-3
    # hpparam_sweep:
    #   type: grid
    #   axes:
    #     - parameter: data.dataset_kwargs.rotation_angle
    #       vals: linspace(0,180,50,endpoint=True)
    #     - parameter: data.dataset_split.restrict_n_samples_train_task
    #       vals:
    #       - 300