config:

  run_script_name: instability_analyzer
  run_script_kwargs:
    instability_sweep: /system/user/publicwork/beck/projects/regularization/erank/outputs/mnist-11.7.3-lenet_rottasks_ft--221125_123651
    score_fn: TAccuracy
    interpolation_factors: [0.0000, 0.2500, 0.5000, 0.7500, 1.0000]
    init_model_idxes_ks_or_every: 3
    train_model_idxes: [100, -1]
    device: 0
    interpolate_linear_kwargs: 
      interpolation_on_train_data: True
      dataloader_kwargs:
        batch_size: 1024
      compute_model_distances: True
    override_files: True
    num_seed_combinations: 1
    hpparam_sweep:
      type: grid
      axes:
        - parameter: data.dataset_kwargs.rotation_angle
          vals: #linspace(0,180,50,endpoint=True)
          - 0.0
          - 3.67346939
          - 11.02040816
          - 18.367346938775512
          - 36.734693877551024
          - 55.10204081632653
          - 73.46938775510205
          - 91.83673469387756
          - 110.20408163265306
          - 128.57142857142858
          - 146.9387755102041
          - 165.3061224489796
          - 172.65306122
          - 180.
        - parameter: data.dataset_split.restrict_n_samples_train_task
          vals:
          - 300